### ISSUE TITLE
Removing Snippets

### ISSUE THREAD

**Issue by aaronbaker315** [ClydeDz/sass-snippet-pack#2]
How do I remove a snippet, the remove button is grayed out.

**Comment by ClydeDz** [comment]
Hi @aaronbaker315, seems like you cannot remove individual snippets. You can only remove the snippet's folder. I'm closing this issue since it's not specific to my snippet pack. For any other Visual Studio specific issues, please feel free to post it [here](https://developercommunity.visualstudio.com/spaces/8/index.html). Thanks!
